spring:
  application:
    name: srv-gestao-pelada
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8080}

app:
  security:
    jwt:
      secret: ${JWT_SECRET:oNZrBH9lWwOO3nSuHmi+aUboal/QPMAXkaHTrzLaFJWf3JVIZDO/fkbM2ZSItReIV8fZbuXwaS+0SmIs1z9SeA==}
      access-token-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:900000}
      refresh-token-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info
